In [1]:
import numpy as np

In [13]:
#¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

np.random.seed(42)
arraybi1 = np.random.random_sample((2,3))
arraybi1


array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [14]:
np.random.seed(42)
arraybi2 = np.random.random_sample((2,3))
arraybi2

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [37]:
#Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, 
# que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

arraytri1 = np.round(np.random.uniform(0,10,size =(2,3,5)),0)
arraytri1


array([[[10.,  2.,  0.,  5.,  2.],
        [ 4.,  7.,  7.,  3.,  5.],
        [ 5.,  6.,  3.,  6., 10.]],

       [[ 5.,  9.,  4.,  4.,  6.],
        [ 7.,  9.,  2.,  5.,  6.],
        [ 8.,  0., 10.,  5.,  3.]]])

In [38]:
arraytri1_unico = np.unique(arraytri1)
arraytri1_unico

array([ 0.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
#Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, 
# con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, 
# extrae sus valores únicos y guarda los datos en una variable.

arraytri2 = np.random.binomial(10,0.3, size= (2,3,5))
arraytri2



array([[[5, 4, 6, 2, 3],
        [3, 6, 1, 2, 2],
        [2, 3, 2, 3, 4]],

       [[5, 1, 2, 4, 2],
        [2, 2, 2, 4, 1],
        [4, 3, 2, 3, 2]]])

In [21]:
arraytri2_unico = np.unique(arraytri2)
arraytri2_unico

array([0, 1, 2, 3, 4, 5, 6])

In [39]:
#Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
#Elementos comunes entre los dos arrays

np.intersect1d(arraytri1_unico, arraytri2_unico)

array([0., 2., 3., 4., 5., 6.])

In [40]:
#Unión de los dos arrays

np.union1d(arraytri1_unico, arraytri2_unico)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
#¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? 
# Extrae los valores númericos
#⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?


np.setdiff1d(arraytri1,arraytri2)



array([ 0.,  7.,  8.,  9., 10.])

In [45]:
np.setdiff1d(arraytri2,arraytri1)

#Setfiff devuelve un array con los valores únicos del primer array, que no están en el segundo. Por lo tanto
#el orden en el que introduzcamos los arrays importa.

array([1])

In [46]:
#Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, 
# con los siguientes nombres array1 y array2.

array1 = np.random.randint(1, 101, 80)
array2 = np.random.randint(1, 101, 80)

In [48]:
array1


array([24, 13, 60,  7, 57, 36, 45, 20, 65,  8, 16, 14, 76, 87, 15, 92, 98,
       66, 32, 87, 63, 86, 51, 25, 58, 63, 62, 22, 58, 58, 86, 49, 52, 42,
       70, 15, 54, 60, 97,  8, 53, 60,  5, 68,  6, 96, 94, 47, 99, 55, 40,
       52, 16, 13, 30, 19, 17, 63, 19, 92, 58, 55, 90, 90, 62, 23,  9, 12,
        1, 58,  1, 34, 96, 48, 89,  1, 16, 61, 64, 63])

In [49]:
array2

array([ 69,  22,  93,  67,  76,  26,  16,  51,  86,  57,  29,  78,  92,
        69,  47,  94,  62,  69,  76,  16,  90,  90,  48,  85,  39, 100,
        33,  94,  23,  10,  69, 100,  34,  52,  95,  10,  19,  58,  96,
         1,  69,   4,  16,  24,  80,   2,  92,  32,  91,  84,  24,  12,
        50,  35,  33,  33,  61,  51,  43,  12,  67,  65,  33,  40,  74,
        43,  44,  29,  13,  12,  95,  46,   2,  35,  87,  81,  90,   8,
        93,  26])

In [50]:
#Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.
array1_unico = np.unique(array1)
array2_unico = np.unique(array2)


In [51]:
array1_unico

array([ 1,  5,  6,  7,  8,  9, 12, 13, 14, 15, 16, 17, 19, 20, 22, 23, 24,
       25, 30, 32, 34, 36, 40, 42, 45, 47, 48, 49, 51, 52, 53, 54, 55, 57,
       58, 60, 61, 62, 63, 64, 65, 66, 68, 70, 76, 86, 87, 89, 90, 92, 94,
       96, 97, 98, 99])

In [52]:
array2_unico

array([  1,   2,   4,   8,  10,  12,  13,  16,  19,  22,  23,  24,  26,
        29,  32,  33,  34,  35,  39,  40,  43,  44,  46,  47,  48,  50,
        51,  52,  57,  58,  61,  62,  65,  67,  69,  74,  76,  78,  80,
        81,  84,  85,  86,  87,  90,  91,  92,  93,  94,  95,  96, 100])

In [54]:
#Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.
array3 = np.setdiff1d(array1, array2)
array3

array([ 5,  6,  7,  9, 14, 15, 17, 20, 25, 30, 36, 42, 45, 49, 53, 54, 55,
       60, 63, 64, 66, 68, 70, 89, 97, 98, 99])

In [55]:
#Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.
array4 = np.setdiff1d(array2,array1)
array4

array([  2,   4,  10,  26,  29,  33,  35,  39,  43,  44,  46,  50,  67,
        69,  74,  78,  80,  81,  84,  85,  91,  93,  95, 100])

In [57]:
#Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.
array5 = np.intersect1d(array1, array2)
array5

array([ 1,  8, 12, 13, 16, 19, 22, 23, 24, 32, 34, 40, 47, 48, 51, 52, 57,
       58, 61, 62, 65, 76, 86, 87, 90, 92, 94, 96])

In [ ]:
#¿Cuál es la relación que existe entre todos estos arrays? 
# 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.


#Ana profe = Simplificar, 
# con las longitudes de los numeros que sacamos, sacar como hay que operar esos numeros para sacar un TRUE

In [58]:
len_array1 = len(array1)
len_array2 = len(array2)
len_array3 = len(array3)
len_array5 = len(array5)

