
<p>Cread tres arrays: de una, dos y tres dimensiones.</p>
<p>Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.</p>
<p>📌 Nota</p>
<ul>
<li>El array de 2 dimensiones debe ser de 2 filas y 3 columnas</li>
<li>El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas</li>
</ul>


In [1]:
import numpy as np



In [4]:
array1 = np.arange(1,5,1)
array1

array([1, 2, 3, 4])

In [6]:
array2 = np.ones((2,2,3), dtype= int)
array2


array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [9]:
array3 = np.random.randint(0,50,(2,3,5))
array3

array([[[37,  3,  5, 33, 18],
        [24, 32, 32, 47, 34],
        [ 7, 42, 12, 10,  5]],

       [[11, 38,  8, 40,  1],
        [46, 35,  3, 47, 14],
        [ 7, 47, 22, 48,  1]]])

Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [26]:
def propiedades_array(array):
     
    print(f"El tamaño del array es",array.size)
    print(f"El tipo de dato del array es", array.dtype)
    print(f"La forma del array es", array.shape)
    print(f"Las dimensiones del array son", array.ndim)

In [27]:
propiedades_array(array1)

El tamaño del array es 4
El tipo de dato del array es int64
La forma del array es (4,)
Las dimensiones del array son 1


In [28]:
propiedades_array(array2)

El tamaño del array es 12
El tipo de dato del array es int64
La forma del array es (2, 2, 3)
Las dimensiones del array son 3


In [29]:
propiedades_array(array3)

El tamaño del array es 30
El tipo de dato del array es int64
La forma del array es (2, 3, 5)
Las dimensiones del array son 3


Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [30]:
array5= np.identity(3)
array5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [31]:
array6 = np.ones_like(array3)
array6

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

Es el momento de hacer algunas operaciones entre arrays:
<ul>
<li>¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?</li>
<li>En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.</li>
<li>Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.</li>
<li>Dividid las dos matricess</li>

In [ ]:
#No se puede sumar por que son dimesiones distintas

In [34]:
array7 = np.ones_like(array5,dtype= int)
array7

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
array5 + array7

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [36]:
array5 * array7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
array5 / array7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])