In [1]:
import numpy as np

In [2]:
#Cread un array de dos dimensiones de 5 filas y 3 columnas. 

array_1 = np.random.random_sample((2,5,3)).round(2)
array_1

array([[[0.8 , 0.24, 0.94],
        [0.09, 0.87, 0.46],
        [0.36, 0.32, 0.28],
        [0.36, 0.16, 0.84],
        [0.93, 0.83, 0.4 ]],

       [[0.38, 0.66, 0.77],
        [0.67, 0.22, 0.05],
        [0.7 , 0.76, 0.32],
        [0.24, 0.58, 0.11],
        [0.74, 0.12, 0.11]]])

In [3]:
# El valor de la primera fila y la segunda columna.
array_1[0,0,1]

0.24

In [4]:
# Los valores de la segunda fila y las dos primeras columnas.
array_1[0,1,:2]

array([0.09, 0.87])

In [5]:
# Extraed las filas pares (incluyendo la 0) y todas las columnas.

array_1[0::2, :]

array([[[0.8 , 0.24, 0.94],
        [0.09, 0.87, 0.46],
        [0.36, 0.32, 0.28],
        [0.36, 0.16, 0.84],
        [0.93, 0.83, 0.4 ]]])

In [6]:
# Extraed los valores que sean mayores que 0.5.

array_1[array_1 > 0.5]

array([0.8 , 0.94, 0.87, 0.84, 0.93, 0.83, 0.66, 0.77, 0.67, 0.7 , 0.76,
       0.58, 0.74])

In [7]:
# Extraed los valores menores que 0.2 o mayores que 0.5

condi1 = array_1 > 0.5
condi2 = array_1 < 0.2

array_1[condi1 | condi2]

array([0.8 , 0.94, 0.09, 0.87, 0.16, 0.84, 0.93, 0.83, 0.66, 0.77, 0.67,
       0.05, 0.7 , 0.76, 0.58, 0.11, 0.74, 0.12, 0.11])

In [8]:
# Cread dos array de tres dimensiones: de 2 matrices, 5 filas y 3 columnas.

array_tri_1 = np.random.randint(0,200, (2,5,3))
array_tri_1

array([[[190,  91,  40],
        [107,  89, 102],
        [ 44, 197,  93],
        [184, 146,   1],
        [ 31,   4,  69]],

       [[115, 171, 145],
        [ 19,  19, 169],
        [118,  35,  39],
        [  1, 198, 116],
        [147, 189, 124]]])

In [9]:
# Cread dos array de tres dimensiones:de 3 matrices, 2 filas y 5 columnas

array_tri_2 = np.random.randint(0,300, (3,2,5))
array_tri_2

array([[[170,  54, 271, 118,  97],
        [293, 211, 220, 218, 287]],

       [[ 55, 182, 289, 160,   2],
        [288,   0, 128,  47,  73]],

       [[ 28, 155, 170, 132, 169],
        [247, 110, 141,  54, 298]]])

In [10]:
# Haced un análisis exploratorio de los array creados.

def propiedades_array(array):
     
    print(f"El tamaño del array es",array.size)
    print(f"El tipo de dato del array es", array.dtype)
    print(f"La forma del array es", array.shape)
    print(f"Las dimensiones del array son", array.ndim)

print (propiedades_array(array_tri_1))
print ("________________________________")
print (propiedades_array(array_tri_2))

El tamaño del array es 30
El tipo de dato del array es int64
La forma del array es (2, 5, 3)
Las dimensiones del array son 3
None
________________________________
El tamaño del array es 30
El tipo de dato del array es int64
La forma del array es (3, 2, 5)
Las dimensiones del array son 3
None


In [11]:
# Sumad los dos arrays. 

suma_arrays = array_tri_1 + array_tri_2
suma_arrays  

# No se puede porque no tienen la misma forma (cada uno tiene diferente número de matrices, filas y columnas)

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

In [12]:
# Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos:
#.reshape()
#.transpose()

suma1 = array_tri_1.reshape((2,15))
suma2 = array_tri_2.reshape((2,15))

In [13]:
suma_arrays = [suma1+suma2]
suma_arrays

[array([[360, 145, 311, 225, 186, 395, 255, 417, 311, 471, 201, 183, 320,
         164,  71],
        [403, 171, 273,  66,  92, 197, 273, 205, 171, 170, 445, 226, 288,
         243, 422]])]

In [17]:
suma_3 = np.transpose(array_tri_2,(1,2,0))

nueva_suma = [suma_3 + array_tri_1]
nueva_suma

[array([[[360, 146,  68],
         [161, 271, 257],
         [315, 486, 263],
         [302, 306, 133],
         [128,   6, 238]],
 
        [[408, 459, 392],
         [230,  19, 279],
         [338, 163, 180],
         [219, 245, 170],
         [434, 262, 422]]])]