In [1]:
import numpy as np

In [2]:
#¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

np.random.seed(42)
arraybi1 = np.random.random_sample((2,3))
arraybi1


array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [3]:
np.random.seed(42)
arraybi2 = np.random.random_sample((2,3))
arraybi2

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [4]:
#Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, 
# que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

arraytri1 = np.round(np.random.uniform(0,10,size =(2,3,5)),0)
arraytri1


array([[[ 1.,  9.,  6.,  7.,  0.],
        [10.,  8.,  2.,  2.,  2.],
        [ 3.,  5.,  4.,  3.,  6.]],

       [[ 1.,  3.,  4.,  5.,  8.],
        [ 2.,  5.,  6.,  0.,  6.],
        [ 2.,  1.,  9., 10.,  8.]]])

In [5]:
arraytri1_unico = np.unique(arraytri1)
arraytri1_unico

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
#Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, 
# con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, 
# extrae sus valores únicos y guarda los datos en una variable.

arraytri2 = np.random.binomial(10,0.3, size= (2,3,5))
arraytri2



array([[[2, 1, 4, 3, 1],
        [3, 1, 5, 2, 4],
        [2, 3, 3, 2, 6]],

       [[4, 5, 5, 3, 5],
        [1, 2, 1, 2, 3],
        [2, 4, 2, 2, 3]]])

In [7]:
arraytri2_unico = np.unique(arraytri2)
arraytri2_unico

array([1, 2, 3, 4, 5, 6])

In [8]:
#Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
#Elementos comunes entre los dos arrays

np.intersect1d(arraytri1_unico, arraytri2_unico)

array([1., 2., 3., 4., 5., 6.])

In [9]:
#Unión de los dos arrays

np.union1d(arraytri1_unico, arraytri2_unico)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
#¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? 
# Extrae los valores númericos
#⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?


np.setdiff1d(arraytri1,arraytri2)



array([ 0.,  7.,  8.,  9., 10.])

In [11]:
np.setdiff1d(arraytri2,arraytri1)

#Setfiff devuelve un array con los valores únicos del primer array, que no están en el segundo. Por lo tanto
#el orden en el que introduzcamos los arrays importa.

array([], dtype=int64)

In [12]:
#Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, 
# con los siguientes nombres array1 y array2.

array1 = np.random.randint(1, 101, 80)
array2 = np.random.randint(1, 101, 80)

In [13]:
array1


array([41, 29, 15, 45, 65, 89, 71,  9, 88,  1,  8, 88, 63, 11, 81,  8, 35,
       35, 33,  5, 41, 28,  7, 73, 72, 12, 34, 33, 48, 23, 62, 88, 37, 99,
       44, 86, 91, 35, 65, 99, 47, 78,  3,  1,  5, 90, 14, 27,  9, 79, 15,
       90, 42, 77, 51, 63, 96, 52, 96,  4, 94, 23, 15, 43, 29, 36, 13, 32,
       71, 59, 86, 28, 66, 42, 45, 62, 57,  6, 28, 28])

In [14]:
array2

array([44, 84, 30, 62, 75, 92, 89, 62, 97,  1, 27, 62, 77,  3, 70, 72, 27,
        9, 62, 37, 97, 51, 44, 24, 79, 59, 32, 96, 88, 52, 62, 58, 52, 12,
       39,  2,  3, 56, 81, 59,  2,  2, 92, 54, 87, 96, 97,  1, 19,  2, 53,
       44, 90, 32, 70, 32, 68, 55, 75, 56, 17, 38, 24, 69, 98, 70, 86, 11,
       16, 97, 73, 59, 70, 80, 93,  3, 20, 59, 36, 19])

In [15]:
#Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.
array1_unico = np.unique(array1)
array2_unico = np.unique(array2)


In [16]:
array1_unico

array([ 1,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 23, 27, 28, 29,
       32, 33, 34, 35, 36, 37, 41, 42, 43, 44, 45, 47, 48, 51, 52, 57, 59,
       62, 63, 65, 66, 71, 72, 73, 77, 78, 79, 81, 86, 88, 89, 90, 91, 94,
       96, 99])

In [17]:
array2_unico

array([ 1,  2,  3,  9, 11, 12, 16, 17, 19, 20, 24, 27, 30, 32, 36, 37, 38,
       39, 44, 51, 52, 53, 54, 55, 56, 58, 59, 62, 68, 69, 70, 72, 73, 75,
       77, 79, 80, 81, 84, 86, 87, 88, 89, 90, 92, 93, 96, 97, 98])

In [18]:
#Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.
array3 = np.setdiff1d(array1_unico, array2_unico)
array3

array([ 4,  5,  6,  7,  8, 13, 14, 15, 23, 28, 29, 33, 34, 35, 41, 42, 43,
       45, 47, 48, 57, 63, 65, 66, 71, 78, 91, 94, 99])

In [19]:
#Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.
array4 = np.setdiff1d(array2_unico,array1_unico)
array4

array([ 2, 16, 17, 19, 20, 24, 30, 38, 39, 53, 54, 55, 56, 58, 68, 69, 70,
       75, 80, 84, 87, 92, 93, 97, 98])

In [20]:
#Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.
array5 = np.intersect1d(array1_unico, array2_unico)
array5

array([ 1,  3,  9, 11, 12, 27, 32, 36, 37, 44, 51, 52, 59, 62, 72, 73, 77,
       79, 81, 86, 88, 89, 90, 96])

In [21]:
#¿Cuál es la relación que existe entre todos estos arrays? 
# 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.


In [25]:
len_array1 = len(array1_unico)
len_array2 = len(array2_unico)
len_array3 = len(array3)              # dif array1_unico
len_array4 = len(array4)             # dif array2_unico
len_array5 = len(array5)            # intersección

len_array1 + len_array2 == len_array3 + len_array4 + 2*len_array5
len_array1 + len_array4 - len_array5 == len_array2 + len_array3 - len_array5

True