<p>1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:</p>

In [2]:
import numpy as np

In [3]:
array1 = np.random.rand(2,3,5).round(1)
array1


array([[[0.4, 0.6, 0.9, 0.9, 0.4],
        [0.9, 0.3, 0.9, 0.1, 0.8],
        [0.9, 0.1, 0.3, 0.8, 0.6]],

       [[0.1, 0.3, 1. , 0.8, 0.2],
        [0.1, 0.4, 0.5, 0.9, 0.3],
        [0.4, 0.8, 0.3, 0.6, 0.4]]])

<p>2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.</p>

In [4]:
media = np.mean(array1).round(1)
media

0.5

<p>3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.</p>

In [5]:
max = np.max(array1).round(1)
max

1.0

<p>4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.</p>

In [6]:
min = np.min(array1).round(1)
min

0.1

<p>5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.</p>
<p>Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:</p>
<ul>
<li>Si el valor del array es igual que la media, se reemplaza por "A".</li>
<li>Si el valor del array es mayor que la media, se reemplaza por "B".</li>
<li>Si el valor del array es menor que la media, se reemplaza por "C".</li>
<li>Si el valor es igual que el máximo, se reemplaza por "D".</li>
<li>Si el valor es igual que el mínimo, se reemplaza por "E".</li>
</ul>

In [7]:
array2 = np.empty_like(array1, dtype= str)
array2

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [8]:
for i in range(array1.shape[0]):
    #i es la dimension
    for j in range(array1.shape[1]):
        #j son las filas
        for k in range(array1.shape[2]):
                #k son las columnas
                print(array1[i,j,k])
                if array1[i,j,k] == media:
                        array2[i,j,k] = "A"
                elif array1[i,j,k] == max:
                        #Ponemos la condición de máximo y mínimo antes porque sino al ser mayor o menor que la media se queda en esa condición
                        array2[i,j,k]= "D"
                elif array1[i,j,k] == min:
                        array2[i,j,k]= "E"  
                elif array1[i,j,k] > media:
                        array2[i,j,k] = "B"
                elif array1[i,j,k] < media:
                        array2[i,j,k] = "C"
                
       
   

0.4
0.6
0.9
0.9
0.4
0.9
0.3
0.9
0.1
0.8
0.9
0.1
0.3
0.8
0.6
0.1
0.3
1.0
0.8
0.2
0.1
0.4
0.5
0.9
0.3
0.4
0.8
0.3
0.6
0.4


In [9]:
array2

array([[['C', 'B', 'B', 'B', 'C'],
        ['B', 'C', 'B', 'E', 'B'],
        ['B', 'E', 'C', 'B', 'B']],

       [['E', 'C', 'D', 'B', 'C'],
        ['E', 'C', 'A', 'B', 'C'],
        ['C', 'B', 'C', 'B', 'C']]], dtype='<U1')

<p>6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.</p<>
En este caso:
Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [10]:
arrayv = np.empty((30), dtype = int)
arrayv

array([4600877379321698714, 4603579539098121011, 4606281698874543309,
       4606281698874543309, 4600877379321698714, 4606281698874543309,
       4599075939470750515, 4606281698874543309, 4591870180066957722,
       4605380978949069210, 4606281698874543309, 4591870180066957722,
       4599075939470750515, 4605380978949069210, 4603579539098121011,
       4591870180066957722, 4599075939470750515, 4607182418800017408,
       4605380978949069210, 4596373779694328218, 4591870180066957722,
       4600877379321698714, 4602678819172646912, 4606281698874543309,
       4599075939470750515, 4600877379321698714, 4605380978949069210,
       4599075939470750515, 4603579539098121011, 4600877379321698714])

In [24]:
for i in range(array2.shape[0]):
    #i es la dimension
    for j in range(array2.shape[1]):
        #j son las filas
        for k in range(array2.shape[2]):
            valor = array2[i,j,k]
            print(j+k+i)
            if valor in ["A", "B"]:
               arrayv[i+j] = 1
            elif valor in ["C", "D"]:
                arrayv[i+j] = 2
            elif valor in ["E"]:
                arrayv[i+j] = 3
          

0
1
2
3
4
1
2
3
4
5
2
3
4
5
6
1
2
3
4
5
2
3
4
5
6
3
4
5
6
7


In [25]:
for i in range(array2.shape[0]):
    for j in range(array2.shape[1]):
        for k in range(array2.shape[2]):
            valor = array2[i, j, k]
            if valor in ["A", "B"]:
                arrayv[i*array2.shape[1]*array2.shape[2] + j*array2.shape[2] + k] = 1
            elif valor in ["C", "D"]:
                arrayv[i*array2.shape[1]*array2.shape[2] + j*array2.shape[2] + k] = 2
            elif valor == "E":
                arrayv[i*array2.shape[1]*array2.shape[2] + j*array2.shape[2] + k] = 3

In [26]:
arrayv

array([2, 1, 1, 1, 2, 1, 2, 1, 3, 1, 1, 3, 2, 1, 1, 3, 2, 2, 1, 2, 3, 2,
       1, 1, 2, 2, 1, 2, 1, 2])

In [28]:
arrayv.reshape((2,3,5))

array([[[2, 1, 1, 1, 2],
        [1, 2, 1, 3, 1],
        [1, 3, 2, 1, 1]],

       [[3, 2, 2, 1, 2],
        [3, 2, 1, 1, 2],
        [2, 1, 2, 1, 2]]])