<p>1.¿Qué diferencia hay entre una Serie y un DataFrame?</p>

In [1]:
#La serie es unidimensional y el data frame es bidimensional

import pandas as pd
import numpy as np

<p>2. Momento de trabajar con Series. Contestad a las siguientes preguntas:</p>
<ul>
<li>Crea dos listas:
<ul>
<li>Una que se llame "valores" que tenga 7 números aleatorios.</li></ul></ul>

In [2]:
valores = np.random.randint(0,7,size = 7)
valores

array([1, 2, 5, 6, 5, 6, 5])

<ul><ul><li>Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.</li>
</ul></ul>

In [3]:
indices = ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sábado", "Domingo"]

<li>A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.</li>

In [4]:
serie1 = pd.Series(valores,indices)
serie1

Lunes        1
Martes       2
Miercoles    5
Jueves       6
Viernes      5
Sábado       6
Domingo      5
dtype: int64

<li>A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.</li>

In [5]:
zip_array = zip(indices,valores)


In [6]:
diccionario = {}

for k,v in zip_array:
    diccionario_peque = {k:v}
    diccionario.update(diccionario_peque)
    
    

In [7]:
diccionario

{'Lunes': 1,
 'Martes': 2,
 'Miercoles': 5,
 'Jueves': 6,
 'Viernes': 5,
 'Sábado': 6,
 'Domingo': 5}

<li>Crea una Serie con el diccionario creado en el punto anterior.</li>

In [8]:
serie_diccionario = pd.Series(diccionario)
serie_diccionario

Lunes        1
Martes       2
Miercoles    5
Jueves       6
Viernes      5
Sábado       6
Domingo      5
dtype: int64

<li>¿Qué forma tiene esta última Serie?</li>

In [9]:
serie_diccionario.shape

(7,)

<li>¿Qué tipo de datos tiene?</li>

In [10]:
serie_diccionario.dtype

dtype('int64')

<li>¿Qué tamaño tiene?</li>

In [11]:
serie_diccionario.size

7

<li>¿Cuáles son los índices de la Serie?</li>

In [12]:
serie_diccionario.index

Index(['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sábado',
       'Domingo'],
      dtype='object')

<li>¿Y los values?</li>

In [13]:
serie_diccionario.values

array([1, 2, 5, 6, 5, 6, 5])

<li>Extraed el valor para el índice "lunes"<li>

In [14]:
serie_diccionario["Lunes"]

1

<li>Extraed el valor para el índice "lunes", "martes" y "miércoles".</li>

In [15]:
serie_diccionario[:3]

Lunes        1
Martes       2
Miercoles    5
dtype: int64

<li>Extraed el valor para el índice "lunes" y "domingo".</li>

In [16]:
serie_diccionario[["Lunes", "Domingo"]] #doble corchete

Lunes      1
Domingo    5
dtype: int64

<p>3. Es el turno de los DataFrames </p>
<p> Cread un array de dos dimensiones con 4 filas y 3 columnas. </p>

In [17]:
array2 = np.random.randint(0,100,(4,3))
array2

array([[82, 86, 98],
       [ 8, 69, 32],
       [90, 38, 85],
       [60, 25, 56]])

<p>Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".</p>

In [18]:
paises = pd.DataFrame(array2, columns = ["España", "Francia", "Italia"])

In [19]:
paises

España  Francia  Italia
0      82       86      98
1       8       69      32
2      90       38      85
3      60       25      56

<p>Usando el loc extraed todas las columnas de la fila de Tailandia.</p>

In [20]:
df = pd.read_csv("medallas.csv", index_col=["País"])

In [21]:
df.loc["Tailandia"]

Unnamed: 0      7
Oro           132
Plata         175
Bronce        278
Name: Tailandia, dtype: int64

<p>Usando el loc extraed todas las columnas de China e Irán.</p>

<p>Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán</p>

In [22]:
df.loc[["China", "Irán"], ["Oro", "Plata", "Bronce"]]


Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

<p>Usando el iloc extraed la información de la India. Devolved todas las columnas.</p>

In [23]:
df.iloc[5]

Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

<p>Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.</p>

In [24]:
df.iloc[1: :2] #seleccionamos impares, para que fuera par cambiamos 1 por un 0

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

<p>Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".</p>

In [25]:
df.iloc[: , -3:] #preguntar clase lunes si el índice se puede quitar

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

<p>Contestad a las siguientes preguntas:</p>
<ul><li>¿Qué país consiguió más de 200 medallas de oro?</li></ul>

In [26]:


medallas_oro = df.loc[df["Oro"] > 200, ["Oro"]]


In [27]:
medallas_oro 

Oro
País               
China          1473
Japón          1032
Corea del Sur   745

<ul><li>¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?</li></ul>

In [28]:
condi1 = df["Oro"] > 200
condi2 = df["Plata"] > 100


In [29]:
df.loc[condi1 & condi2, ["Plata", "Oro"]]

Plata   Oro
País                      
China            994  1473
Japón           1037  1032
Corea del Sur    663   745

<ul><li>¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?</li></ul>

In [30]:
condi3 = df["Oro"] > 200
condi4 = df["Bronce"] > 700

In [31]:
df.loc[condi3 | condi4, ["Bronce", "Oro"]]

Bronce   Oro
País                       
China             720  1473
Japón             985  1032
Corea del Sur     827   745

<p>Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna. </p>

In [32]:
df1 = df.drop(columns =["Unnamed: 0"])

In [33]:
df1

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

<p>Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.</p>

In [34]:
df.insert(4, "total", df["Oro"] + df["Plata"] + df["Bronce"])

IndexError: index 4 is out of bounds for axis 0 with size 3

In [ ]:
df1

Oro  Plata  Bronce  total
País                                       
China            1473    994     720   3187
Japón            1032   1037     985   3054
Corea del Sur     745    663     827   2235
Irán              179    181     197    557
Kazajistán        155    158     224    537
India             154    202     315    671
Tailandia         132    175     278    585
Indonesia         112    131     240    483
China Taipéi       99    144     276    519
Corea del Norte    91    120     235    446